apiVersion: v1
kind: Service
metadata:
  name: domain-aoeai-test-app
  labels:
    app: aoeai-test-app
spec:
  hostname: app-dns
  type: NodePort
  selector:
    app: aoeai-test-app
  ports:
  - name: foo
    port: 80
    targetPort: 8080
    # 可选字段
    # 默认情况下，为了方便起见，Kubernetes 控制平面会从某个范围内分配一个端口号（默认：30000-32767）
    nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aoeai-test-app
spec:
  selector:
    matchLabels:
      app: aoeai-test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: aoeai-test-app
    spec:
      tolerations:
      - key: "foo"
        operator: "Equal"
        value: "bar"
        effect: "NoSchedule"
      containers:
      - name: aoeai-test-app
        image: registry.cn-shenzhen.aliyuncs.com/aoeai/test:0.0.2
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    name: busybox
spec:
  hostname: busybox-2
  subdomain: default-subdomain
  containers:
  - image: registry.cn-shenzhen.aliyuncs.com/aoeai/test:0.0.2
    name: busybox
  tolerations:
    - key: "foo"
      operator: "Equal"
      value: "bar"
      effect: "NoSchedule"

      busybox-12.default-subdomain.default.svc.cluster.local